global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ai-code-review-api"
    static_configs:
      - targets: ["host.docker.internal:8000"]
    metrics_path: "/metrics"

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
